version: '3.7'
services:
  node1:
    image: atlassian/jira-software:7.13.2
    ports:
      - 9090:8080
      - 8443:8443
    volumes:
      - ./artifacts/jira-home-node1:/var/atlassian/application-data/jira:z
      - ./artifacts/jira-shared-home:/var/atlassian/jira-shared-home:z
    environment:
      CATALINA_OPTS: -Datlassian.cluster.scale=true -DjvmRoute=node1
    networks:
      - softnet

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt:z
      - ./letsencrypt:/var/lib/letsencrypt:z
      - ./acme-challenge:/var/www/acme-challenge:z
    command: /bin/sh -c ["mkdir", "-p", "/letsencrypt"]
    command: /bin/sh -c ["mkdir", "-p", "/var/www/acme-challenge"]
    command: /bin/sh -c [ "sleep 10", "chown", "www-data:www-data", "/var/www/acme-challenge" ]
    command: ["certonly", "--webroot", "--webroot-path", "/var/www/acme-challenge", "-d", "***", "--agree-tos", "--email", "***", "--non-interactive", "--quiet"]
    networks:
      - softnet

  proxy:
    image: haproxy:2.6
    ports:
      - 8081:80
      - 443:8443
    volumes:
      - ./haproxy.cfg:/etc/haproxy/haproxy.cfg:z
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:z
     # - ./keys/:/etc/haproxy/
    networks:
      - softnet

  database:
    image: postgres:10.5-alpine
    volumes:
      - ./artifacts/postgresql-data:/var/lib/postgresql/data:z
      - ./postgre-db-init.sql:/docker-entrypoint-initdb.d/postgre-db-init.sql:z
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
    networks:
      - softnet

networks:
  haproxy_network:
    external: true
  softnet:
    driver: bridge
